'use strict';
let current=null;
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=n=>n==null?'—':`${n>=0?'+':''}${Number(n).toFixed(2)}%`;
const date=s=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Hong_Kong',hour12:false}):'尚无记录';
const tone=n=>n==null?'neutral':n>=0?'positive':'negative';
function link(s){let u;try{u=new URL(s.url);if(u.protocol!=='https:')return '';}catch{return '';}return `<a href="${escape(u.href)}" target="_blank" rel="noopener noreferrer">${escape(s.title||u.hostname)}</a>`;}
function quoteStatus(q,d){if(q.status==='INVALID')return ['无效报价','stale'];const et=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const hour=Number(parts.find(p=>p.type==='hour').value),minute=Number(parts.find(p=>p.type==='minute').value);const active=(d.market.trading_dates||[]).includes(et)&&(hour*60+minute>=570&&hour*60+minute<960);const age=(Date.now()-new Date(q.exchange_at).getTime())/1000;if(active)return age>=0&&age<=90&&d.market.status!=='DATA_BLOCKED'?['正常盘 · 新鲜','fresh']:['陈旧／采集失败','stale'];return ['最近正常盘',''];}
function spark(code,d){const rows=(d.market.history||[]).filter(r=>r.values?.[code]!=null);const unique=[];for(const row of rows){if(!unique.length||row.source_times?.[code]!==unique.at(-1).source_times?.[code])unique.push(row);}if(unique.length<2)return '';const values=unique.map(r=>Number(r.values[code])),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1;const points=values.map((v,i)=>`${i/(values.length-1)*280},${34-(v-lo)/span*28}`).join(' ');return `<svg class="spark" viewBox="0 0 280 38" aria-label="已实际采集的报价趋势" role="img"><polyline points="${points}" fill="none" stroke="#54788a" stroke-width="1.5"/></svg>`;}
function render(d){current=d;const quotes=d.market.quotes||[],qmap=Object.fromEntries(quotes.map(q=>[q.symbol,q]));$('#session-label').textContent=`美东 ${d.clock.trade_date} · 正常盘开盘 ${date(d.clock.regular_open_HK)} · ${d.clock.phase==='IDLE'?'当前在交易窗口外':d.clock.phase}`;$('#data-state').textContent=d.market.status==='DATA_BLOCKED'?'行情采集受阻 · 暂停新增风险':(d.market.message||'尚未完成行情采集');$('#latency').textContent=`最后采集 ${date(d.market.captured_at)} ｜ 接口耗时 ${d.market.api_elapsed_seconds??'待测'}秒`;
$('#indices').innerHTML=['US..DJI','US..IXIC','US..SPX'].map(code=>{const q=qmap[code];if(!q)return `<article class="index-card"><div class="index-name">${escape(code)}<span class="tag stale">待核</span></div><div class="index-number">—</div><p class="footnote">未获取指数报价，不以ETF冒充。</p></article>`;const [label,cls]=quoteStatus(q,d);return `<article class="index-card"><div class="index-name">${escape(q.name)}<span class="tag ${cls}">${label}</span></div><div class="index-number">${fmt(q.price)}</div><div class="delta ${tone(q.change_pct)}">${pct(q.change_pct)} <span class="neutral">较前收盘</span></div>${spark(code,d)}<div class="index-meta">${escape(code)} ｜ 报价时间 ${date(q.exchange_at)}<br>来源 Futu · 采集频率不代表行情延迟</div></article>`;}).join('');renderWatch();
$('#action-status').innerHTML=`<span class="action-status">${escape(d.actions.status||'WAIT')}</span>`;$('#actions').innerHTML=(d.actions.cards?.length?d.actions.cards:[{status:'WAIT',reason:d.actions.reason||['当前没有已冻结并完成验证的日内候选。']}]).map(c=>`<article class="action-card"><h3>${escape(c.symbol||'暂不操作')} · ${escape(c.status)}</h3><p>${escape((c.reason||[]).join('；'))}</p>${c.quantity&&!c.expired?`<p>条件股数 ${escape(c.quantity)}股<br>触发 ${escape(c.trigger)} ｜ 最高限价 ${escape(c.entry_limit)}<br>硬保护参考 ${escape(c.planned_hard_stop)} ｜ 结构失效位 ${escape(c.structural_exit_level)}<br>有效至 ${date(c.valid_until_HK||c.valid_until_ET)}</p>`:''}</article>`).join('');
const p=d.portfolio;$('#capital').innerHTML=[[p.planned_trading_cash_usd,'日内计划'],[p.unallocated_original_usd,'原本金暂不分配'],[p.reserve_usd,'备用金'],['200','每月额外定投']].map(([v,l])=>`<div><strong>US$${fmt(v)}</strong><span>${l}</span></div>`).join('');
$('#impact-events').innerHTML=(d.research.events||[]).filter(e=>e.review_status==='verified').slice(0,5).map(e=>`<article class="event"><h3>${escape(e.title||e.fact)}</h3><div class="footnote">发布 ${date(e.published_at)} ｜ 核验 ${date(e.reviewed_at)} ｜ ${escape(e.fact_type||'事实')}</div><dl class="event-grid"><dt>发生了什么</dt><dd>${escape(e.fact)}</dd><dt>影响哪些资产</dt><dd>${escape((e.affected_assets||[]).map(a=>`${a.symbol}：${a.path}`).join('；'))}</dd><dt>利多 / 利空</dt><dd>${escape(e.direction)} <span class="neutral">（推断，非价格预测）</span></dd><dt>影响强度</dt><dd>${escape(e.strength)} · ${escape(e.strength_reason)}</dd><dt>时间范围</dt><dd>${escape(e.horizon)}</dd><dt>后续验证</dt><dd>${escape((e.validation||[]).join('；'))}</dd></dl><details><summary>为什么这样理解 / 什么会推翻判断</summary><p>${escape(e.mechanism)}</p><p>${escape(e.falsification||'尚待补充反向验证条件')}</p></details><div class="sources">${(e.sources||[]).map(link).join('')}</div></article>`).join('')||'<p class="empty">当前没有已核验、与观察清单有经济关联的事件。缺少数据不代表没有事件。</p>';
const now=Date.now(),week=now+7*86400000;const ev=(d.calendar.events||[]).filter(e=>new Date(e.at).getTime()>=now&&new Date(e.at).getTime()<=week);$('#calendar').innerHTML=ev.length?`<div class="table-wrap"><table><thead><tr><th>香港时间</th><th>事件</th><th>影响观察</th><th>来源</th></tr></thead><tbody>${ev.map(e=>`<tr><td>${date(e.at)}</td><td>${escape(e.title)}<small>未来安排，实际值未发生</small></td><td>${escape(e.watch||'利率、美元及市场反应')}</td><td>${link({url:e.source,title:e.source_name||'原发布方'})}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">未来7天已核实日历尚未填充；不能据此推断无事件。</p>';$('#coverage').textContent=`日历覆盖：${(d.calendar.coverage||[]).map(s=>`${s.name} ${s.status}`).join(' · ')}。更新时间 ${date(d.calendar.asof)}`;
const brief=d.brief;$('#brief-content').innerHTML=brief.sections?.length?`<p class="section-note">${escape(brief.label||'资产晨报')} ｜ 实际生成 ${date(brief.asof)} ｜ ${escape(brief.coverage_note||'')}</p>${brief.sections.map(s=>`<section class="brief-section"><h3>${escape(s.title)}</h3><p>${escape(s.text)}</p>${s.sources?`<div class="sources">${s.sources.map(link).join('')}</div>`:''}</section>`).join('')}`:'<p class="empty">晨报尚未生成；不会用旧报告替换今天的晨报。</p>';
$('#deployment-state').textContent=`自动化：${d.automation.morning?.enabled?'晨报已设':'晨报待设'} / ${d.automation.trading?.enabled?'交易检查已设':'交易检查待设'} ｜ 远程入口：${d.deployment.remote_enabled?'已配置':'等待身份登录与部署'}`;
}
function renderWatch(){if(!current)return;const query=$('#search').value.toLowerCase();const w=current.watchlist;const rows=[...(w.core||[]),...(w.discretionary||[]),...(current.frozen.candidates||[]).map(r=>({...r,role:'当日日内冻结候选'}))];const qmap=Object.fromEntries((current.market.quotes||[]).map(q=>[q.symbol,q]));$('#watchlist').innerHTML=rows.filter(r=>(r.symbol+' '+(r.name||'')).toLowerCase().includes(query)).map(r=>{const q=qmap[r.symbol];return `<tr><td><strong>${escape(r.symbol.replace('US.',''))}</strong><small>${escape(r.name||'当日候选')}</small></td><td>${q?fmt(q.price):'待采集'}</td><td class="${tone(q?.change_pct)}">${pct(q?.change_pct)}</td><td>${escape(r.role||'研究观察')}<small>${escape((r.factors||[]).slice(0,3).join(' · '))}</small></td></tr>`;}).join('')||'<tr><td colspan="4">没有匹配的观察资产。</td></tr>';$('#watch-note').textContent=`日内冻结池：${current.frozen.status||'NOT_FROZEN'}，${current.frozen.candidates?.length||0}只。研究清单可以较广，日内清单最多3只。SNDK不会自动进入日内候选。`;}
async function refresh(){try{const r=await fetch('/api/dashboard',{cache:'no-store'});if(r.status===401){location.assign('/login');return;}if(!r.ok)throw new Error('service');render(await r.json());}catch{$('#data-state').textContent='看板连接中断 · 不依赖旧卡新增风险';$('#data-state').className='negative';}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==b.dataset.view));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));$('#page-title').textContent=b.textContent.replace(/^\d+\s*/,'').trim();}));$('#refresh').addEventListener('click',refresh);$('#search').addEventListener('input',renderWatch);setInterval(()=>{$('#local-time').textContent=new Date().toLocaleString('zh-CN',{timeZone:'Asia/Hong_Kong',hour12:false});},1000);setInterval(refresh,15000);refresh();
